services:
  cow-session-docker-compse:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cow-session
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"

